"""
Moving a WordPress site without losing anything.
================================================

A migration is the one operation in this toolkit that can destroy a business in
an afternoon, so the design is defensive in three specific ways.

**It is a state machine on disk.** Every stage records that it happened. A run
that dies halfway can be read afterwards — what completed, what the sites look
like now, and what the way out is. Re-running never repeats a completed stage.

**Nothing irreversible happens without a verified backup on both sides.** Not a
backup that was taken: a backup that was proven restorable. And no backup is
deleted until Lior says the migration is finished.

**Pruning never touches content.** Caches, logs, transients and stale plugin
backups are fair game. Media, posts, users and orders are not, at any size. If
the archive is still over the limit after safe pruning, the run stops and shows
what is large — it does not start deleting things to fit.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from ..change_guard.checks import Check, CheckReport, visible_text
from ..schema import Result
from .limits import HARD_ARCHIVE_LIMIT, ServerLimits, check_archive, human

Runner = Callable[[list[str]], tuple[int, str, str]]    # argv -> (code, stdout, stderr)
Fetcher = Callable[[str], tuple[int, str]]

#: In order. Each stage may only run once its predecessors are done.
STAGES = (
    "preflight",        # what the two sites can do, and what the limits are
    "backup_source",    # full backup of the site we are moving
    "backup_target",    # full backup of whatever we are about to overwrite
    "verify_backups",   # prove both restore before anything is touched
    "export",           # build the .wpress
    "size_gate",        # the 500MB hard limit, measured on the finished file
    "import",           # write to the target — requires explicit approval
    "postcheck",        # what must be true afterwards
)

#: Safe to drop from an export. Every one of these is regenerated by WordPress
#: or by a plugin on demand.
PRUNABLE = {
    "cache":            "קבצי cache של תוספים (wp-content/cache)",
    "plugin_backups":   "גיבויים ישנים שתוספים יצרו (ai1wm-backups, updraft)",
    "transients":       "transients פגי תוקף בבסיס הנתונים",
    "logs":             "קבצי לוג ודיבאג (debug.log, error_log)",
    "revisions":        "גרסאות ישנות של פוסטים — התוכן הנוכחי לא נוגע",
    "spam_comments":    "תגובות שסומנו כספאם ובאשפה",
    "temp":             "קבצים זמניים ותיקיות upgrade",
}

#: Never, at any size. Deleting one of these to fit under a limit is how a
#: migration turns into a data loss incident.
NEVER_PRUNE = (
    "wp-content/uploads — מדיה",
    "פוסטים, דפים ותוכן",
    "משתמשים והרשאות",
    "הזמנות ומוצרים (WooCommerce)",
    "רשומות טפסים",
    "טבלאות של תוספים שלא מזוהות כ-cache",
)

#: Plugins whose licence is bound to the domain and needs re-activating after a
#: move. Not detectable from the HTML — this is the list to walk manually.
LICENCE_BOUND = (
    "Elementor Pro", "WP Rocket", "Gravity Forms", "ACF Pro",
    "WPML", "Rank Math PRO", "Yoast SEO Premium", "WooCommerce extensions",
)


# ═══════════════════════════════════════════════════════
#  WP-CLI first, browser only if there is no other way
# ═══════════════════════════════════════════════════════

@dataclass
class ToolingReport:
    """What the installed All-in-One WP Migration actually offers."""

    has_wpcli: bool = False
    has_plugin: bool = False
    subcommands: list[str] = field(default_factory=list)
    detail: str = ""

    @property
    def can_export(self) -> bool:
        return self.has_plugin and bool({"backup", "export"} & set(self.subcommands))

    @property
    def can_import(self) -> bool:
        return self.has_plugin and bool({"restore", "import"} & set(self.subcommands))

    @property
    def method(self) -> str:
        """`wp-cli` when the installed version supports it, `browser` otherwise."""
        return "wp-cli" if (self.can_export and self.can_import) else "browser"


_SUBCOMMAND = re.compile(r"^\s{2,}(?:ai1wm\s+)?([a-z][a-z0-9-]*)\s{2,}\S", re.M)


def detect_tooling(run: Runner) -> ToolingReport:
    """Ask the installed plugin what it can do, rather than assuming a version.

    The free and paid builds of All-in-One WP Migration ship different WP-CLI
    surfaces, and both have changed across releases. Parsing `wp help ai1wm` is
    the only answer that is true for the site in front of us.
    """
    report = ToolingReport()

    code, out, err = run(["wp", "--info"])
    if code != 0:
        report.detail = f"WP-CLI לא זמין: {(err or out).strip()[:120]}"
        return report
    report.has_wpcli = True

    code, out, err = run(["wp", "help", "ai1wm"])
    if code != 0:
        report.detail = (
            "WP-CLI קיים אבל All-in-One WP Migration לא חושף פקודות — "
            "נמשיך דרך ממשק הניהול"
        )
        return report

    report.has_plugin = True
    report.subcommands = sorted(set(_SUBCOMMAND.findall(out)))
    report.detail = (
        f"פקודות זמינות: {', '.join(report.subcommands)}"
        if report.subcommands else
        "wp help ai1wm רץ אבל לא הוחזרו תת-פקודות — נמשיך דרך ממשק הניהול"
    )
    return report


# ═══════════════════════════════════════════════════════
#  State — resumable and idempotent
# ═══════════════════════════════════════════════════════

@dataclass
class StageState:
    name: str
    status: str = "pending"          # pending · done · failed · skipped
    detail: str = ""
    at: str = ""


@dataclass
class MigrationState:
    migration_id: str
    source: str
    target: str
    stages: dict[str, StageState] = field(default_factory=dict)
    archive_path: str = ""
    archive_bytes: int = 0
    method: str = ""
    import_approved: bool = False
    backups_released: bool = False
    created_at: str = ""

    @classmethod
    def new(cls, migration_id: str, source: str, target: str) -> "MigrationState":
        return cls(
            migration_id=migration_id, source=source, target=target,
            stages={name: StageState(name) for name in STAGES},
            created_at=_now(),
        )

    def stage(self, name: str) -> StageState:
        return self.stages.setdefault(name, StageState(name))

    def is_done(self, name: str) -> bool:
        return self.stage(name).status == "done"

    @property
    def completed(self) -> list[str]:
        return [name for name in STAGES if self.is_done(name)]

    @property
    def next_stage(self) -> str | None:
        return next((name for name in STAGES if not self.is_done(name)), None)

    @property
    def failed_stage(self) -> str | None:
        return next((n for n in STAGES if self.stage(n).status == "failed"), None)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def begin(state: MigrationState, name: str) -> Result:
    """Guard a stage: refuse to repeat it, refuse to run it out of order.

    Running the same migration script twice is the normal way a resumed run
    starts, so a completed stage is a skip and not an error.
    """
    if name not in STAGES:
        return Result.failure("unknown_stage", f"שלב לא מוכר: {name}")
    if state.is_done(name):
        return Result.failure(
            "already_done",
            f"שלב {name} כבר הושלם ב-{state.stage(name).at} — מדלג",
            recoverable=True,
        )

    position = STAGES.index(name)
    missing = [s for s in STAGES[:position] if not state.is_done(s)]
    if missing:
        return Result.failure(
            "out_of_order",
            f"אי אפשר להריץ {name} לפני שהושלמו: {', '.join(missing)}",
            recoverable=True,
            missing=missing,
        )
    return Result.success("ready", f"שלב {name} מוכן לריצה")


def complete(state: MigrationState, name: str, detail: str = "") -> MigrationState:
    stage = state.stage(name)
    stage.status, stage.detail, stage.at = "done", detail, _now()
    return state


def mark_failed(state: MigrationState, name: str, detail: str) -> MigrationState:
    stage = state.stage(name)
    stage.status, stage.detail, stage.at = "failed", detail, _now()
    return state


def save(state: MigrationState, directory: Path) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{state.migration_id}.json"
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(state.to_dict(), fh, ensure_ascii=False, indent=2)
    return path


def load(migration_id: str, directory: Path) -> Result:
    path = directory / f"{migration_id}.json"
    if not path.exists():
        return Result.failure("migration_missing", f"לא נמצאה העברה בשם {migration_id}")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return Result.failure(
            "migration_corrupt",
            f"קובץ מצב ההעברה פגום: {exc}. אל תמשיך — בדוק ידנית מה מצב שני האתרים.",
            recoverable=False,
        )
    state = MigrationState(
        migration_id=raw["migration_id"], source=raw.get("source", ""),
        target=raw.get("target", ""),
        stages={k: StageState(**v) for k, v in (raw.get("stages") or {}).items()},
        archive_path=raw.get("archive_path", ""),
        archive_bytes=int(raw.get("archive_bytes") or 0),
        method=raw.get("method", ""),
        import_approved=bool(raw.get("import_approved")),
        backups_released=bool(raw.get("backups_released")),
        created_at=raw.get("created_at", ""),
    )
    return Result.success("loaded", f"העברה {migration_id} נטענה", state=state)


# ═══════════════════════════════════════════════════════
#  Pruning — safe categories only
# ═══════════════════════════════════════════════════════

@dataclass
class PrunePlan:
    items: list[tuple[str, int]] = field(default_factory=list)   # (category, bytes)
    refused: list[str] = field(default_factory=list)

    @property
    def savings(self) -> int:
        return sum(size for _, size in self.items)

    def render(self) -> str:
        lines = [f"  {PRUNABLE[name]}: {human(size)}" for name, size in self.items]
        if self.refused:
            lines.append("  לא נגענו: " + " · ".join(self.refused))
        return "\n".join(lines)


def plan_pruning(inventory: dict[str, int]) -> PrunePlan:
    """Decide what may be dropped from the export.

    `inventory` maps a category name to bytes. Anything not in `PRUNABLE` is
    refused by name, so an unexpected category can never be quietly swept into
    the "safe to delete" pile.
    """
    plan = PrunePlan()
    for name, size in sorted(inventory.items(), key=lambda item: -item[1]):
        if name in PRUNABLE and size > 0:
            plan.items.append((name, int(size)))
        elif name not in PRUNABLE:
            plan.refused.append(name)
    return plan


def size_gate(archive_bytes: int, limits: ServerLimits, largest: list[tuple[str, int]] | None = None) -> Result:
    """The hard stop. Measured on the finished archive, never on an estimate."""
    verdict = check_archive(archive_bytes, limits)
    if verdict:
        return verdict

    breakdown = ""
    if largest:
        breakdown = "\n\nהקבצים הגדולים:\n" + "\n".join(
            f"  {human(size):>9}  {name}" for name, size in largest[:10]
        )

    return Result.failure(
        "archive_too_large",
        verdict.detail + breakdown + (
            "\n\nלא ממשיכים אוטומטית. האפשרויות: להעלות את המגבלות בשרת היעד, "
            "להעביר את המדיה בנפרד דרך rsync/FTP ולייצא בלי uploads, "
            "או לפצל את ההעברה. מדיה ותוכן לא נמחקים כדי להיכנס לגבול."
        ),
        recoverable=True,
        archive_bytes=archive_bytes,
        hard_limit=HARD_ARCHIVE_LIMIT,
        problems=verdict.data.get("problems", []),
    )


#: All-in-One WP Migration writes a 4377-byte header before every file
#: (255 name + 14 size + 12 mtime + 4096 path) and terminates the archive with
#: one such block of zeros. A truncated download has no terminator.
WPRESS_BLOCK = 4377

#: Below this, a `.wpress` is an error page or a failed export, not a site.
MIN_ARCHIVE_BYTES = 1024 * 1024


def verify_archive(path: Path) -> Result:
    """Structural proof that an archive is complete, before it is relied on.

    This is not a restore test — only a restore proves a restore. What it does
    prove is that the file is a `.wpress`, that it is not an error page saved
    with the wrong extension, and that it was not truncated in transfer, which
    is how most "the backup was corrupt" stories actually start.
    """
    if not path.exists():
        return Result.failure(
            "archive_missing", f"קובץ הגיבוי לא נמצא: {path}", recoverable=False
        )

    size = path.stat().st_size
    if size < MIN_ARCHIVE_BYTES:
        return Result.failure(
            "archive_too_small",
            f"הקובץ {human(size)} בלבד — זו כמעט תמיד הודעת שגיאה שנשמרה "
            "בשם .wpress ולא גיבוי",
            recoverable=False,
        )

    with open(path, "rb") as fh:
        head = fh.read(255)
        fh.seek(-WPRESS_BLOCK, 2)
        tail = fh.read(WPRESS_BLOCK)

    name = head.split(b"\x00", 1)[0]
    if not name or not all(32 <= byte < 127 for byte in name):
        return Result.failure(
            "archive_not_wpress",
            "הקובץ לא נפתח בשם קובץ תקין — כנראה אינו .wpress",
            recoverable=False,
        )

    if tail != b"\x00" * WPRESS_BLOCK:
        return Result.failure(
            "archive_truncated",
            "לקובץ חסר בלוק הסיום — הוא נקטע בהעברה. אל תייבא אותו.",
            recoverable=False,
        )

    return Result.success(
        "archive_verified",
        f"{human(size)} · מבנה תקין ולא קטוע",
        size=size, path=str(path),
    )


def largest_entries(path: Path, limit: int = 10) -> list[tuple[str, int]]:
    """The biggest files inside a `.wpress`, largest first.

    The archive is a flat sequence of 4377-byte headers each followed by its
    file body, so the whole inventory can be walked by seeking — without
    extracting anything. This is what turns "too large" into an answer.
    """
    entries: list[tuple[str, int]] = []
    try:
        with open(path, "rb") as fh:
            while True:
                header = fh.read(WPRESS_BLOCK)
                if len(header) < WPRESS_BLOCK or header == b"\x00" * WPRESS_BLOCK:
                    break
                name = header[:255].split(b"\x00", 1)[0].decode("utf-8", "replace")
                raw_size = header[255:269].split(b"\x00", 1)[0]
                prefix = header[281:].split(b"\x00", 1)[0].decode("utf-8", "replace")
                try:
                    size = int(raw_size or 0)
                except ValueError:
                    break
                entries.append((f"{prefix}/{name}".lstrip("/"), size))
                fh.seek(size, 1)
    except OSError:
        return []

    return sorted(entries, key=lambda item: -item[1])[:limit]


def verify_backup_pair(source: Result, target: Result) -> Result:
    """Both backups must be provably restorable before the import is allowed."""
    failures = []
    if not source:
        failures.append(f"גיבוי המקור: {source.detail}")
    if not target:
        failures.append(f"גיבוי היעד: {target.detail}")

    if failures:
        return Result.failure(
            "backups_unverified",
            "אי אפשר להתחיל ייבוא:\n  - " + "\n  - ".join(failures)
            + "\nגיבוי שלא נבדק הוא לא גיבוי.",
            recoverable=False,
            failures=failures,
        )
    return Result.success("backups_verified", "שני הגיבויים אומתו כשחזוריים")


# ═══════════════════════════════════════════════════════
#  What must be true after the move
# ═══════════════════════════════════════════════════════

_IMG_SRC    = re.compile(r"""<img[^>]+src=["']([^"']+)""", re.I)
_CANONICAL  = re.compile(r"""<link[^>]+rel=["']canonical["'][^>]*href=["']([^"']+)""", re.I)
_ROBOTS     = re.compile(r"""<meta[^>]+name=["']robots["'][^>]*content=["']([^"']+)""", re.I)
_FORMS      = re.compile(r"<form\b", re.I)
_ELEMENTOR_CSS = re.compile(r"""uploads/elementor/css/post-(\d+)\.css""", re.I)


def postcheck(
    url: str,
    old_domain: str,
    new_domain: str,
    fetch: Fetcher,
    expected_forms: int = 0,
    robots_txt: str | None = None,
) -> CheckReport:
    """The checklist that catches the expensive mistakes.

    The first three are the ones that actually cost money: a page left on
    noindex from the staging environment, a Search & Replace that missed the
    old domain, and images that 404 because uploads never arrived.
    """
    checks: list[Check] = []

    try:
        status, html = fetch(url)
    except Exception as exc:
        return CheckReport([Check("הדף נטען", False, f"שגיאה בטעינה: {exc}")])

    checks.append(Check("הדף מחזיר 200", status == 200, f"סטטוס {status}"))
    if status != 200:
        return CheckReport(checks)

    checks.append(_check_noindex(html, robots_txt))
    checks.append(_check_old_domain(html, old_domain))
    checks.append(_check_canonical(html, new_domain))
    checks.append(_check_mixed_content(html))
    checks.append(_check_forms(html, expected_forms))
    checks.append(_check_elementor_css(html, fetch, new_domain))
    checks.append(_check_images(html, fetch))
    checks.append(
        Check(
            "רישיונות תוספים",
            True,
            "לבדוק ידנית: " + ", ".join(LICENCE_BOUND),
            breaking=False,
        )
    )
    return CheckReport(checks)


def _check_noindex(html: str, robots_txt: str | None) -> Check:
    """The classic, and the most expensive: noindex carried over from staging."""
    meta = _ROBOTS.search(html)
    meta_noindex = bool(meta and "noindex" in meta.group(1).lower())

    blocked_in_robots = False
    if robots_txt:
        for line in robots_txt.splitlines():
            if re.match(r"^\s*disallow:\s*/\s*$", line, re.I):
                blocked_in_robots = True

    if meta_noindex and blocked_in_robots:
        detail = "הדף noindex וגם robots.txt חוסם הכל"
    elif meta_noindex:
        detail = "meta robots מכיל noindex — כנראה נגרר מסביבת הפיתוח"
    elif blocked_in_robots:
        detail = "robots.txt מכיל Disallow: / — האתר חסום לסריקה"
    else:
        detail = "האתר פתוח לסריקה"
    return Check("האתר מאונדקס", not (meta_noindex or blocked_in_robots), detail)


def _check_old_domain(html: str, old_domain: str) -> Check:
    if not old_domain:
        return Check("Search & Replace", True, "לא צוין דומיין ישן", breaking=False)
    hits = len(re.findall(re.escape(old_domain), html, re.I))
    return Check(
        "Search & Replace הושלם",
        hits == 0,
        "לא נותרו אזכורים לדומיין הישן" if hits == 0 else
        f"{hits} אזכורים ל-{old_domain} נשארו בדף — "
        "הרץ wp search-replace כולל הטבלאות הסריאליות",
    )


def _check_canonical(html: str, new_domain: str) -> Check:
    match = _CANONICAL.search(html)
    if not match:
        return Check("קנוניקל", True, "אין קנוניקל בדף", breaking=False)
    value = match.group(1)
    ok = not new_domain or new_domain.lower() in value.lower()
    return Check(
        "הקנוניקל מצביע לדומיין החדש", ok,
        value if ok else f"{value} — עדיין מצביע לאתר הישן",
    )


def _check_mixed_content(html: str) -> Check:
    insecure = re.findall(r"""(?:src|href)=["']http://([^"'/]+)""", html, re.I)
    external = {host for host in insecure if not host.startswith("www.w3.org")}
    return Check(
        "אין תוכן מעורב",
        not external,
        "כל הנכסים ב-HTTPS" if not external else
        f"נכסים ב-HTTP: {', '.join(sorted(external)[:3])}",
    )


def _check_forms(html: str, expected: int) -> Check:
    now = len(_FORMS.findall(html))
    ok = now >= expected
    return Check(
        "הטפסים במקומם", ok,
        f"{now} טפסים (צפויים {expected})" + ("" if ok else " — נעלם טופס"),
    )


def _check_elementor_css(html: str, fetch: Fetcher, new_domain: str) -> Check:
    """Elementor's per-post CSS is generated, and a move invalidates it.

    A missing file means the page renders with the theme's styles only, which
    looks like the design broke — because it did.
    """
    refs = _ELEMENTOR_CSS.findall(html)
    if not refs:
        return Check("Elementor CSS", True, "הדף אינו Elementor", breaking=False)

    url_match = re.search(
        r"""["']([^"']*uploads/elementor/css/post-\d+\.css[^"']*)""", html, re.I
    )
    if not url_match:
        return Check("Elementor CSS", True, f"{len(refs)} קבצי CSS מקושרים", breaking=False)

    href = url_match.group(1)
    if href.startswith("//"):
        href = "https:" + href
    elif href.startswith("/"):
        href = f"https://{new_domain}{href}"

    try:
        status, _ = fetch(href)
    except Exception as exc:
        return Check("Elementor CSS נטען", False, f"שגיאה: {exc}")
    return Check(
        "Elementor CSS נטען",
        status == 200,
        f"סטטוס {status}" + ("" if status == 200 else
                             " — הרץ Elementor > Tools > Regenerate CSS"),
    )


def _check_images(html: str, fetch: Fetcher, sample: int = 5) -> Check:
    """Sample the images. A 404 here means uploads did not make the trip."""
    sources = [src for src in _IMG_SRC.findall(html) if not src.startswith("data:")][:sample]
    if not sources:
        return Check("תמונות נטענות", True, "אין תמונות בדף", breaking=False)

    broken: list[str] = []
    for src in sources:
        target = "https:" + src if src.startswith("//") else src
        if not target.startswith("http"):
            continue
        try:
            status, _ = fetch(target)
        except Exception:
            broken.append(target)
            continue
        if status != 200:
            broken.append(f"{target} ({status})")

    return Check(
        "תמונות נטענות",
        not broken,
        f"{len(sources)} נבדקו, כולן תקינות" if not broken else
        f"{len(broken)} תמונות שבורות — ייתכן ש-uploads לא הועבר: {broken[0]}",
    )


# ═══════════════════════════════════════════════════════
#  When it breaks in the middle
# ═══════════════════════════════════════════════════════

_RECOVERY = {
    None: "שום שלב לא הושלם — אף אתר לא נגע. אפשר להתחיל מחדש.",
    "preflight": "נאספו מגבלות בלבד. אף אתר לא נגע.",
    "backup_source": "גיבוי המקור קיים. אתר היעד עדיין לא נגע.",
    "backup_target": "שני הגיבויים קיימים אבל טרם אומתו. אף ייבוא לא בוצע.",
    "verify_backups": "שני הגיבויים אומתו. עדיין לא נוצר קובץ ייצוא.",
    "export": "קובץ הייצוא נוצר. אתר היעד לא נגע — אפשר למחוק את הקובץ ולהתחיל מחדש.",
    "size_gate": "הקובץ עבר את מגבלת הגודל. הייבוא עוד לא התחיל.",
    "import": (
        "הייבוא בוצע. אתר היעד נדרס — אם משהו נשבר, שחזר אותו מגיבוי היעד "
        "לפני כל ניסיון נוסף."
    ),
    "postcheck": "ההעברה הושלמה ונבדקה.",
}


def recovery_instructions(state: MigrationState) -> str:
    """What state the two sites are in right now, and the way out.

    The dangerous moment is a failure during `import`: the target has been
    partly overwritten, and the only correct move is a restore from the target
    backup rather than a second import attempt on top of the first.
    """
    completed = state.completed
    last = completed[-1] if completed else None
    lines = [_RECOVERY.get(last, "מצב לא מוכר — בדוק ידנית את שני האתרים.")]

    failed = state.failed_stage
    if failed:
        lines.append(f"השלב שנכשל: {failed} — {state.stage(failed).detail}")

    if failed == "import" or (last == "import" and "postcheck" not in completed):
        lines.append(
            "אזהרה: כשל בזמן ייבוא משאיר את אתר היעד במצב חלקי. "
            "שחזר מגיבוי היעד — אל תריץ ייבוא נוסף על גבי הקיים."
        )
    if not state.backups_released:
        lines.append("הגיבויים נשמרים. הם יימחקו רק באישור מפורש.")
    return "\n".join(lines)


def release_backups(state: MigrationState, confirmed: bool) -> Result:
    """Backups are only deletable after an explicit, final approval."""
    if not confirmed:
        return Result.failure(
            "not_confirmed",
            "מחיקת גיבויים דורשת אישור מפורש. עד אז הם נשארים.",
        )
    if not state.is_done("postcheck"):
        return Result.failure(
            "postcheck_incomplete",
            "בדיקות אחרי ההעברה לא הושלמו — הגיבויים נשארים.",
        )
    state.backups_released = True
    return Result.success("released", "הגיבויים סומנו כניתנים למחיקה")


def text_length(html: str) -> int:
    """Visible text length, reused from the publish gate for layout comparison."""
    return len(visible_text(html))
